docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Intro: intro.md
    - Reference:
        - Messages: message.md
        - Parts: part.md
site_name: laminas-mime
site_description: laminas-mime
repo_url: 'https://github.com/laminas/laminas-mime'
